---
- name: Install docker repo
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"

- name: Add the docker repo key
  apt_key: 
    keyserver: p80.pool.sks-keyservers.net 
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Ensure latest docker is installed
  apt:
    pkg: docker-engine
    state: latest
    install_recommends: yes
    update_cache: yes  

- name: Add learner user to docker and admin groups
  user:
    name: learner
    groups: learner,docker,admin
    append: yes     

- name: nopasswod for sudo
  lineinfile: 
    dest: /etc/sudoers 
    state: present
    regexp: '^%ADMIN ALL\=' 
    line: '%ADMIN ALL=(ALL) NOPASSWD:ALL' 
    validate: 'visudo -cf %s'
